version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Starting Flask App"
      - nohup python cicd_app.py &
